# Generated by Django 4.1 on 2022-09-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
