# Generated by Django 4.1 on 2022-09-03 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_subject_title_alter_subtopic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.subtopic'),
        ),
    ]
