# Generated by Django 4.1 on 2022-09-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_followers_user_following_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answered_Question',
        ),
    ]
